dist: trusty
sudo: false
language: cpp

compiler:
  - gcc
  - clang

before_install:
  # g++7
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3-6
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-program-options-dev

  # g++7
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi

  # clang 3-6
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3-6; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3-6"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - kalakris-cmake
    packages:
     - g++-7
     - clang-3-6
     - libboost-all-dev
     - libboost-program-options-dev
     - llvm-toolchain-3.6
     - libssl1.0-dev
     - cmake

script:
  - $CXX --version
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2 

notifications:
  email:
    recipients:
      - michal.p.karol+travis@gmail.com
    on_success: never
    on_failure: always
