dist: xenial
sudo: false
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libboost-program-options-dev
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-7 fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90 fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - boost-latest
      - kalakris-cmake
    packages:
     - libstdc++-6-dev
     - g++-6
     - libboost-all-dev
     - libboost-program-options-dev
     - llvm-toolchain-3.6
     - libssl1.0-dev
     - cmake

script:
  - $CXX --version
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2 

notifications:
  email:
    recipients:
      - michal.p.karol+travis@gmail.com
    on_success: never
    on_failure: always
