dist: xenial
sudo: false
language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - boost-latest
      - kalakris-cmake
    packages:
     - g++-7
     - libboost-all-dev
     - libboost-program-options-dev
     - llvm-toolchain-3.6
     - libssl1.0-dev
     - cmake

script:
  - $CXX --version
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2 

notifications:
  email:
    recipients:
      - michal.p.karol+travis@gmail.com
    on_success: never
    on_failure: always
